### ISSUE TITLE
Calendar deisgn

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ux#1]
In the current design for calendar (https://github.com/telerik/kendo-ux/blob/master/themes/default/calendar.psd) does not show how the calendar for kendo-jquery looks.

The other design we have -- https://github.com/telerik/kendo-ux/blob/ccd30d08084d9dad39ef5e7ab8124f56d4a01595/themes/default/components.theme.default.psd -- shows the calendar looking very, very differently.

**Comment by yordanov** [comment]
Kendo jQuery Calendar design has been added:

https://github.com/telerik/kendo-ux/blob/master/themes/default/calendar-jquery.psd
